services:
  postgres_db:
    image: postgres:18.3-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: nestjs_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres_db:5432/mydatabase?schema=public"
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - postgres_db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: angular_frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # No port 4200 here! It's running on Nginx (80)
    networks:
      - app-net
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-net
    depends_on:
      - backend
      - frontend

networks:
  app-net:
    driver: bridge
